### ISSUE TITLE
Setting up development

### ISSUE THREAD

**Issue by rubydesign** [ruby-x/rubyx#30]
I am starting this as a new thread, so #19 stays on issue.
Here we can discuss about how to set up for development. Sort of like email, but github links to code and issues work better. (I may make a beginner guide out of the result)
Since i don't know anything about you, we'll start at the top. If there are any questions, just ask. Remember there are no stupid question, we all started at zero sometime.

So the first thing is to clone rubyx.

Then bundle. For that you need a working ruby, version 2.4 or higher

Then you set up your screen with an editor and terminal, and start guard (bundle exec guard) in the terminal.It is helpful if you can see the terminal output partially, while the editor is open.

The open the file lib/ruby/logical_statement.rb    and press save.
Guard should then run the test   test/ruby/test_logical_statement.rb automatically , and it should pass.

Look at the test, see what it does. Look at the statement class and figure out how. Maybe compare to the ruby/if_statement above it.

I know this may seem a lot, but we'll just take one step at a time. Just tell me where you are at, what you understand.

**Comment by chhavikirtani2000** [comment]
Hey. I am in the process of learning ruby by following online tutorials, and I have been using atom for the same.
In atom I was not able to run Guardfile, and hence I tried running test_logical_statement.rb directly.
But I get this error:
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
Could not find rake-12.3.3 in any of the sources
Run `bundle install` to install missing gems
I have searched the whole net but I could not find how to run a specific command(gem install bundler:2.14) in atom.io.
Please provide some help if possible. Or please tell me alternate ways to run a ruby code.

Thanks a lot for your time.

**Comment by rubydesign** [comment]
Ok, there are two things you can do, let's start with the warning

If you open the Gemfile.lock , right at the bottom you'll see where bundler makes it's mark (bundled with...). Just remove those two lines. Then run the bundle command again and it should work.

The better way is just to run the command gem install bundler:2.1.4
as it says, and that will take care of it.  (btw what platform, ie os and mri, are you on?)

The  second is really a network error. The gem clearly exists https://rubygems.org/gems/rake/versions/12.3.3
If you have network connection it may be too slow to the american west cost. Try a different place (caffe/university ?) and different time. I am assuming you are in India, so try when America is sleeping.

Once you have managed to bundle you will not need to do that again for a long time.

Oh and you run bundle from a command line, not inside atom.

And the last: There is no other way to run ruby code. There was a time before the bundler, but i usually refer to it as Dark Ages :-) Try to read up on what it does, so you understand the process.

**Comment by chhavikirtani2000** [comment]
Okay, thanks a lot.
I will give it a try and get back.

**Comment by chhavikirtani2000** [comment]
Hi. So I was able to resolve the previous errors but now it is stuck at an error:
Could not find ffi-1.11.1-x64-mingw32 in any of the sources
Run `bundle install` to install missing gems
I tried installing ffi using:
gem install ffi -v '1.11.1' --source 'https://rubygems.org/'
But the following error occurred
ERROR:  Error installing ffi:
        The last version of ffi (= 1.11.1) to support your Ruby & RubyGems was 1.11.1. Try installing it with `gem install ffi -v 1.11.1`
        ffi requires Ruby version >= 2.2, < 2.7.dev. The current ruby version is 2.7.0.0.

So do I need to have a ruby version less than 2.7 to be able to setup?

**Comment by rubydesign** [comment]
Okey dokey, i'm running 2.6.5 , so never had that.

I updated the Gemfle.lock , please do a git pull and try again.

Generally speaking, you could have done that locally, the command to update just ffi (or try to) is "bundle update ffi" . The new (still compatible)  1.12.2 does not have the < 2.7 restriction. 
good luck

**Comment by chhavikirtani2000** [comment]
Okay, thank you. I was finally able to set up. 
I will work on this now - "Look at the test, see what it does. Look at the statement class and figure out how. Maybe compare to the ruby/if_statement above it."
Thanks for your time.

**Comment by chhavikirtani2000** [comment]
Hi. I was looking into the code and I am not sure of a few things. It will be great if you can explain.
In file test_logical_statement.rb:
`def simple
      compile( "@a and @b")`
Here what does the compile method do exactly? I was not able to find any answer online.
In file logical_statement.rb, where does the initialize function gets called?
`def initialize(name , left , right)
      @name , @left , @right = name , left , right
    end`

**Comment by rubydesign** [comment]
Ok, so when you paste code, try and do it with indentation intact, by using insert code in this editor. Or copy/paste a link to the code on github. You do this by going to the repo, clicking through to the file, then the line, then copy the url, eg like https://github.com/ruby-x/rubyx/blob/master/test/ruby/test_logical_statement.rb#L7

You see the class does an include. `include` is a method in ruby, the argument must be a module. So you look for `module RubyTests` . If you use atom, you can do a global search by Ctr+Shif+F .
You'll find RubyTests, and the compile method here https://github.com/ruby-x/rubyx/blob/master/test/ruby/helper.rb#L9

Another way to achieve this is to global search for `compile` , especially for it's definition, so `def compile` , and especially in test directory (third line in search allows restriction to directory)

The second question you can tackle similarly, you just need to search for `LogicalStatement.new` . `initialize` is **always** called by the class function `new` . You'll find it in the `RubyCompiler`.

To understand how that works you'll have to read up on Processors in the parser gem https://github.com/whitequark/parser . Play around with examples, especially it's output of the test code snippets (somthing like `1 and 2` )

**Comment by chhavikirtani2000** [comment]
Okay!
But coming back to the #19 can you explain the issue more? 
It will be good to have good knowledge of the problem so that I know exactly what to look at.

**Comment by rubydesign** [comment]
Second one first, yes. 

First: explain more is a bit vague. Explain to me what you do understand, and we can go from there

**Comment by chhavikirtani2000** [comment]
I think we need to implement the assert equal statements in logical statement form, i.e., statements that will return boolean values.
I am not sure if I am right, please correct me if I misunderstood something.
Thanks.

**Comment by rubydesign** [comment]
I think from our discussion so far and your answer, i would say this is too difficult for you.
For me newbie means someone new to this project, but you are also new to ruby. You will need someone local, like the rgsoc coaches, to spend more time with you.

You can try something easier is you want. I have made a distinct, much more contained, issue, #37 

you can comment on the issue there if you want to continue to ask. I will close this and remove your comment in no 19.
