### ISSUE TITLE
implement Parfait word start_with

### ISSUE THREAD

**Issue by rubydesign** [ruby-x/rubyx#37]
In https://github.com/ruby-x/rubyx/blob/master/lib/parfait/word.rb

implement the method start_with. Only with another string for now.

https://ruby-doc.org/core-2.6/String.html#method-i-start_with-3F

(off course including tests)

**Comment by chhavikirtani2000** [comment]
Hi.
I have implemented the start_with function for word.rb but I am not sure what you mean by including tests. Does it mean I need to create a new file something like test_word.rb, similar to test_object.rb created for object.rb inside parfait?

**Comment by rubydesign** [comment]
Ok! Well done.

If you run guard (or `bundle exec guard` ) in the rubyx directory, and then save the word.rb file, the existing tests should run automatically. For word there are actually two, but to run the first second by hand would be 
`ruby test/parfait/test_word2.rb`

You should add test methods to that file to check that your code does what one would expect. Ideally 2 cases that return true, and one that return fails.
Look at https://github.com/ruby-x/rubyx/blob/master/test/parfait/test_word2.rb#L81

If you create a topic branch and push that, i can have a look.
read Eg: https://github.com/dchelimsky/rspec/wiki/Topic-Branches
and i wrote https://github.com/ruby-x/rubyx/blob/master/BeginnersGuide.md

**Comment by chhavikirtani2000** [comment]
Raised PR. Please have a look and let me know.
Thanks

**Comment by rubydesign** [comment]
Ok, some misunderstanding of OO. What language is your strongest?

Your test should look something like
```
def test_start_ok
    one = Parfait.new_word("hello")
    two = Parfait.new_word("hel")
    assert one.starts_with(two)
end
``` 

So your method only takes one arg ( "hel" )
No new instance variables
Also for loops are hardly ever used in ruby, if you could use a while that would be nicer
And i would start with a length test, if the arg is longer than self, it can't possibly return true.

**Comment by chhavikirtani2000** [comment]
Oh Okay. I made the necessary changes and updated the PR. Please have a look and let me know.
I am used to coding in C++, but I have experience in python too.
Thanks.
